// Mocks generated by Mockito 5.4.6 from annotations
// in disasteraid_app/test/auth_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:disasteraid_app/core/storage/secure_storage.dart' as _i6;
import 'package:disasteraid_app/features/auth/data/auth_repository.dart' as _i3;
import 'package:disasteraid_app/features/auth/domain/user_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<({String token, _i2.UserModel user})> register({
    String? email,
    String? phone,
    required String? password,
    required String? name,
    required String? role,
    String? cnic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #name: name,
            #role: role,
            #cnic: cnic,
          },
        ),
        returnValue: _i4.Future<({String token, _i2.UserModel user})>.value((
          token: _i5.dummyValue<String>(
            this,
            Invocation.method(
              #register,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
                #name: name,
                #role: role,
                #cnic: cnic,
              },
            ),
          ),
          user: _FakeUserModel_0(
            this,
            Invocation.method(
              #register,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
                #name: name,
                #role: role,
                #cnic: cnic,
              },
            ),
          )
        )),
        returnValueForMissingStub:
            _i4.Future<({String token, _i2.UserModel user})>.value((
          token: _i5.dummyValue<String>(
            this,
            Invocation.method(
              #register,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
                #name: name,
                #role: role,
                #cnic: cnic,
              },
            ),
          ),
          user: _FakeUserModel_0(
            this,
            Invocation.method(
              #register,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
                #name: name,
                #role: role,
                #cnic: cnic,
              },
            ),
          )
        )),
      ) as _i4.Future<({String token, _i2.UserModel user})>);

  @override
  _i4.Future<({String token, _i2.UserModel user})> login({
    String? email,
    String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
          },
        ),
        returnValue: _i4.Future<({String token, _i2.UserModel user})>.value((
          token: _i5.dummyValue<String>(
            this,
            Invocation.method(
              #login,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
              },
            ),
          ),
          user: _FakeUserModel_0(
            this,
            Invocation.method(
              #login,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
              },
            ),
          )
        )),
        returnValueForMissingStub:
            _i4.Future<({String token, _i2.UserModel user})>.value((
          token: _i5.dummyValue<String>(
            this,
            Invocation.method(
              #login,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
              },
            ),
          ),
          user: _FakeUserModel_0(
            this,
            Invocation.method(
              #login,
              [],
              {
                #email: email,
                #phone: phone,
                #password: password,
              },
            ),
          )
        )),
      ) as _i4.Future<({String token, _i2.UserModel user})>);

  @override
  _i4.Future<_i2.UserModel> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i6.SecureStorageService {
  @override
  _i4.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserRole(_i2.UserRole? role) => (super.noSuchMethod(
        Invocation.method(
          #saveUserRole,
          [role],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveUserId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
