export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    ME: '/auth/me',
  },
  DONATIONS: {
    LIST: '/donations',
    DETAILS: (id: number) => `/donations/${id}`,
    APPROVE: (id: number) => `/donations/${id}/approve`,
  },
  WITHDRAWALS: {
    LIST: '/withdrawals',
    APPROVE: (id: number) => `/withdrawals/${id}/approve`,
    REJECT: (id: number) => `/withdrawals/${id}/reject`,
  },
  CAMPAIGNS: {
    LIST: '/campaigns',
    CREATE: '/campaigns',
    UPDATE: (id: number) => `/campaigns/${id}`,
    UPDATE_STATUS: (id: number) => `/campaigns/${id}/status`,
  },
  USERS: {
    LIST: '/users',
    UPDATE: (id: number) => `/users/${id}`,
    SUSPEND: (id: number) => `/users/${id}/suspend`,
    REACTIVATE: (id: number) => `/users/${id}/reactivate`,
  },
  ADMIN: {
    DONATIONS: '/admin/donations',
    DONATIONS_STATS: '/admin/donations/stats',
    WITHDRAWALS: '/admin/withdrawals',
    WITHDRAWALS_STATS: '/admin/withdrawals/stats',
    CAMPAIGNS: '/admin/campaigns',
    CAMPAIGNS_STATS: '/admin/campaigns/stats',
    USERS: '/admin/users',
    USERS_STATS: '/admin/users/stats',
    OPERATIONAL: '/admin/operational',
    LEDGER: '/admin/ledger',
    AUDIT_LOGS: '/admin/audit-logs',
  },
  NGO: {
    STATS: '/ngo/dashboard/stats',
    PROFILE: '/ngo/profile',
    CAMPAIGNS: '/ngo/campaigns',
    PUBLIC: (id: number) => `/ngo/public/${id}`,
  },
  GOODS_CAMPAIGNS: {
    LIST:   '/goods-campaigns',
    MINE:   '/goods-campaigns/mine',
    BY_ID:  (id: number) => `/goods-campaigns/${id}`,
    CREATE: '/goods-campaigns',
    UPDATE: (id: number) => `/goods-campaigns/${id}`,
    DELETE: (id: number) => `/goods-campaigns/${id}`,
  },
  GOODS_DONATIONS: {
    MINE:         '/goods-donations/mine',
    NGO:          '/goods-donations/ngo',
    AVAILABLE:    '/goods-donations/available',
    FOR_REVIEW:   '/goods-donations/for-review',
    ADMIN_ALL:    '/admin/goods-donations',
    BY_ID:        (id: number) => `/goods-donations/${id}`,
    CLAIM:        (id: number) => `/goods-donations/${id}/claim`,
    DELIVER:      (id: number) => `/goods-donations/${id}/deliver`,
    APPROVE:      (id: number) => `/goods-donations/${id}/approve`,
    REJECT:       (id: number) => `/goods-donations/${id}/reject`,
    ADMIN_OVERRIDE: (id: number) => `/admin/goods-donations/${id}/override`,
  },
};
